name: 'feature-tracker'
services:
  ft-webapp:
    image: sivaprasadreddy/ft-webapp
    container_name: ft-webapp
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - API_GATEWAY_URL=http://ft-api-gateway:8989
      - OAUTH2_SERVER_URL=http://keycloak:9191
    ports:
      - "8080:8080"
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 700m

  ft-api-gateway:
    image: sivaprasadreddy/ft-api-gateway
    container_name: ft-api-gateway
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - FEATURE_SERVICE_URL=http://ft-feature-service:8081
    ports:
      - "8989:8989"
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 700m

  ft-feature-service:
    image: sivaprasadreddy/ft-feature-service
    container_name: ft-feature-service
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - DB_URL=jdbc:postgresql://features-db:5432/postgres
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      - OAUTH2_SERVER_URL=http://keycloak:9191
      - KAFKA_BROKER=kafka:9093
    ports:
      - "8081:8081"
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 700m

  ft-notification-service:
    image: sivaprasadreddy/ft-notification-service
    container_name: ft-notification-service
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - KAFKA_BROKER=kafka:9093
    ports:
      - "8083:8083"
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 700m

  ft-user-service:
    image: sivaprasadreddy/ft-user-service
    container_name: ft-user-service
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - DB_URL=jdbc:postgresql://users-db:5432/postgres
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
    ports:
      - "8084:8084"
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 700m