name: 'feature-tracker'
services:
  features-db:
    image: postgres:17
    container_name: features-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "55432:5432"

  keycloak:
    image: quay.io/keycloak/keycloak:26.0.2
    command: [ 'start-dev', '--import-realm', '--http-port=9191' ]
    container_name: keycloak
    hostname: keycloak
    volumes:
      - ./realm-config:/opt/keycloak/data/import
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin1234
    ports:
      - "9191:9191"
    deploy:
      resources:
        limits:
          memory: 2gb
