version: '3'

vars:
  GOOS: "{{default OS .GOOS}}"
  INFRA_DC_FILE: "infra.yml"
  APPS_DC_FILE: "apps.yml"
  SLEEP_CMD: '{{if eq .GOOS "windows"}}timeout{{else}}sleep{{end}}'

tasks:
  default:
    cmds:
      - task: test

  start_infra:
    cmds:
      - "docker compose -f {{.INFRA_DC_FILE}} up -d"

  stop_infra:
    cmds:
      - "docker compose -f {{.INFRA_DC_FILE}} stop"
      - "docker compose -f {{.INFRA_DC_FILE}} rm -f"

  restart_infra:
    cmds:
      - task: stop_infra
      - task: sleep
      - task: start_infra

  docker_pull:
    cmds:
      - "docker pull sivaprasadreddy/ft-feature-service"
      - "docker pull sivaprasadreddy/ft-user-service"
      - "docker pull sivaprasadreddy/ft-notification-service"
      - "docker pull sivaprasadreddy/ft-api-gateway"
      - "docker pull sivaprasadreddy/ft-config-server"
      - "docker pull sivaprasadreddy/feature-tracker-angular"

  start:
    cmds:
      - task: docker_pull
      - "docker compose -f {{.INFRA_DC_FILE}} up -d"
      - task: sleep
      - "docker compose -f {{.APPS_DC_FILE}} up -d"

  devstart:
    cmds:
      - "./local-build.sh"
      - task: stop
      - "docker compose -f {{.INFRA_DC_FILE}} up -d"
      - task: sleep
      - "docker compose -f {{.APPS_DC_FILE}} up -d"

  stop:
    cmds:
      - "docker compose -f {{.INFRA_DC_FILE}} -f {{.APPS_DC_FILE}} stop"
      - "docker compose -f {{.INFRA_DC_FILE}} -f {{.APPS_DC_FILE}} rm -f"

  restart:
    cmds:
      - task: stop
      - task: sleep
      - task: start

  sleep:
    vars:
      DURATION: "{{default 5 .DURATION}}"
    cmds:
      - "{{.SLEEP_CMD}} {{.DURATION}}"